fix(datastore): wrap failures to result when applying remote update events
aws-amplify/amplify-swift pull request #3187
Opened 2023-08-28 18:25 UTC by 5d

## Issue \#

https://github.com/aws-amplify/amplify-swift/issues/1903

## Description

We apply remote update events in batch. The existing code converts all the update operations into a `Future<Void, DataStoreError>`, and merge them into one stream. The problem arises when a `Future` completes with an error; it causes the entire stream to terminate as an error. This behavior is unintentional and results in some update operations being silently discarded.

The solution here is simply change `Future<Void, DataStoreError>` to `Future<Result<Void, DataStoreError>, Never>`, which wraps the failure to a result type and makes the operation never fail.

## General Checklist

- [ ] Added new tests to cover change, if needed
- [ ] Build succeeds with all target using Swift Package Manager
- [ ] All unit tests pass
- [ ] All integration tests pass
- [ ] Security oriented best practices and standards are followed (e.g. using input sanitization, principle of least privilege, etc)
- [ ] Documentation update for the change if required
- [x] PR title conforms to conventional commit style
- [ ] New or updated tests include `Given When Then` inline code documentation and are named accordingly `testThing_condition_expectation()`
- [ ] If breaking change, documentation/changelog update with migration instructions

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-08-29 19:23 UTC, lawmicha requested changes
Changes LGTM. Can we link to some passing integration tests workflows against this change?

2023-09-01 14:53 UTC, lawmicha commented
> 9b17942e Deployed 2 days ago by [5d](https://github.com/5d) via [datastore-lazy-load-test / datastore-integration-lazy-load-test-watchOS #494](https://github.com/aws-amplify/amplify-swift/actions/runs/6018410565)

I see only two failures in one test suite

Failing tests:
	DataStoreConnectionScenario1Tests.testDeleteAndGetProjectReturnsNilWithSync()
	DataStoreConnectionScenario1Tests.testListProjectsByTeamID()


Clicked on re-run

2023-09-01 16:14 UTC, 5d commented
> > [9b17942](https://github.com/aws-amplify/amplify-swift/commit/9b17942eedc5e4258ba54d03005984d34d8792cc) Deployed 2 days ago by [5d](https://github.com/5d) via [datastore-lazy-load-test / datastore-integration-lazy-load-test-watchOS #494](https://github.com/aws-amplify/amplify-swift/actions/runs/6018410565)
> 
> I see only two failures in one test suite
> 
> Failing tests: DataStoreConnectionScenario1Tests.testDeleteAndGetProjectReturnsNilWithSync() DataStoreConnectionScenario1Tests.testListProjectsByTeamID()
> 
> Clicked on re-run

Yeah, our datastore integration test failed randomly. It rarely succeed. https://github.com/aws-amplify/amplify-swift/actions/workflows/integ_test_datastore.yml

2023-09-05 18:51 UTC, lawmicha approved these changes

2023-09-06 17:05 UTC, merged